EventPanels: добавлены панели с разными темами + рефакторинг стилей и кода
MarkSmirnov13/Momentum pull request #9
Opened 2020-04-18 19:47 UTC by MarkSmirnov13

2020-04-18 20:11 UTC, MaximLukianchuk requested changes

2020-04-18 20:11 UTC, MaximLukianchuk commented on src/components/EventCard/EventCard.js
> +const EventCard = ({ name, time, date, children }) => {
Мне кажется нужно прокинуть className через пропсы

2020-04-18 20:11 UTC, MaximLukianchuk commented on src/components/EventCard/_theme/center/EventCard_theme_center.js
> +import cn from "classnames";
го кавычки односимвольные?

2020-04-18 20:11 UTC, MaximLukianchuk commented on src/components/EventCard/_theme/center/EventCard_theme_center.js
> +        const moment = getParsedTime(moments, false);
зач передавать false, если он по дефолту будет undef, если просто не передавать?

2020-04-18 20:11 UTC, MaximLukianchuk commented on src/components/EventCard/_theme/center/EventCard_theme_center.js
> +    {theme: 'center'},
пробельчики

2020-04-18 20:11 UTC, MaximLukianchuk commented on src/components/EventCard/_theme/center/EventCard_theme_center.js
> +    (WrapperComponent) => ({ name, theme, date }) => {
без скобочек мб?

2020-04-18 20:11 UTC, MaximLukianchuk commented on src/components/EventCard/_theme/column/EventCard_theme_column.js
> +import cn from "classnames";
по кавычкам то же самое

2020-04-18 20:11 UTC, MaximLukianchuk commented on src/App.js
>  				activePanel={activePanel}
какие-то жесткие отступы, или мне кажется?

2020-04-18 20:11 UTC, MaximLukianchuk commented on src/App.js
>  	useEffect(() => {
отступы пиздэц

2020-04-18 20:11 UTC, MaximLukianchuk commented on src/components/EventCard/_theme/column/EventCard_theme_column.js
> +    {theme: 'column'},
отступы

2020-04-18 20:11 UTC, MaximLukianchuk commented on src/components/EventCard/_theme/column/EventCard_theme_column.js
> +    (WrapperComponent) => ({ name, theme, date }) => {
скобули кикнем?

2020-04-18 20:11 UTC, MaximLukianchuk commented on src/components/EventCard/_theme/inline/EventCard_theme_inline.js
> +    (WrapperComponent) => ({ name, theme, date }) => {
скобушки

2020-04-18 20:11 UTC, MaximLukianchuk commented on src/components/EventCard/_theme/square/EventCard_theme_square.js
> +    (WrapperComponent) => ({ name, theme, date }) => {
скобы

2020-04-18 20:11 UTC, MaximLukianchuk commented on src/components/EventCard/index.js
> +export { default as EventCardBase } from './EventCard'
точку с запятой забыл

2020-04-18 20:11 UTC, MaximLukianchuk commented on src/components/Header/Header.css
> +    transform: translate(0, -50%);}
фигурную скобку на новую строку бы

2020-04-18 20:11 UTC, MaximLukianchuk commented on src/components/Header/Header.js
> +import PanelHeaderButton from "@vkontakte/vkui/dist/components/PanelHeaderButton/PanelHeaderButton";
кавычки не те

2020-04-18 20:11 UTC, MaximLukianchuk commented on src/store/actions/events.js
> +      { id: 2, name: 'Днюха', date: new Date(2020, 8, 2), type: 'red-theme', theme: 'inline' },
я запутался, а в чем разница между type и theme??

2020-04-18 20:11 UTC, MaximLukianchuk commented on src/utils/getParsedTime.js
> + * Функция, которая высчитывает корректный размер шрифта для EventCard с темой 'inline',
может тогда поместить ее в отдельный файл?

2020-04-18 20:11 UTC, MaximLukianchuk commented on src/utils/getParsedTime.js
> +        return 'body1'
;

2020-04-18 20:11 UTC, MaximLukianchuk commented on src/utils/getParsedTime.js
> +    if (size <= 7) {
предлагаю заменить magic digits на константы с понятным названием

2020-04-18 20:11 UTC, MaximLukianchuk commented on src/utils/withMod.js
> + * Функция обертка, которая позволяет создать кастомные HOC'и, которые будут навешиватся в зависимости
1) создавать
2) навешиваться
3) пришедшей

2020-04-18 20:12 UTC, MaximLukianchuk commented on src/components/EventCard/_theme/center/EventCard_theme_center.js
> +import cn from "classnames";
ну и везде тогда так

2020-04-18 20:12 UTC, MaximLukianchuk commented on src/components/EventCard/_theme/center/EventCard_theme_center.js
> +    {theme: 'center'},
и везде ниже)

2020-04-18 20:13 UTC, MaximLukianchuk commented on src/components/EventCard/_theme/center/EventCard_theme_center.js
> +    (WrapperComponent) => ({ name, theme, date }) => {
ниже такое же будет

2020-04-19 14:28 UTC, MarkSmirnov13 commented on src/components/EventCard/EventCard.js
> +const EventCard = ({ name, time, date, children }) => {
в данном случае он нигде больше не используется

2020-04-19 14:29 UTC, MarkSmirnov13 commented on src/components/EventCard/_theme/center/EventCard_theme_center.js
> +        const moment = getParsedTime(moments, false);
по умолчанию он будет `true`

2020-04-21 11:18 UTC, merged